### ISSUE TITLE
about tag

### ISSUE THREAD

**Issue by CoderOverflow** [Paperspace/fastai-docker#2]
Tag：1.0-CUDA9.2-base-3.0-v1.0.6

What does the tag mean？ Is there any details？

**Comment by captn3m0** [comment]
What I gleaned from reading the Dockerfile:

- `1.0-`: ???
- `CUDA9.2`: Uses nvidia CUDA 9.2 release
- `base-`: ???
- `3.0-`: course v3
- `v1.0.6`: Release of this docker container: https://github.com/Paperspace/fastai-docker/tree/v1.0.6

**Comment by Renart-fox** [comment]
First number looks like the Dockerfile version.
Base is the type of the image. Other values for Nvidia images are "runtime" and "devel".
