### ISSUE TITLE
Docker to use the GPU still using the old parameter

### ISSUE THREAD

**Issue by bopbi** [Paperspace/fastai-docker#7]
on the https://github.com/Paperspace/fastai-docker/blob/master/fastai-v4/README.md

its still using 
```sudo docker run --runtime=nvidia -d -p 8888:8888 paperspace/fastai:1.0-CUDA9.2-base-3.0-v1.0.6```

on the recent docker it now use
```sudo docker run --gpus all -d -p 8888:8888 paperspace/fastai:1.0-CUDA9.2-base-3.0-v1.0.6```

**Comment by jaredscheib** [comment]
Thanks for reporting this @bopbi! Would you be willing to submit a PR for this change? We'd love your contribution! cc @dkobran

**Comment by bopbi** [comment]
PR created, please review https://github.com/Paperspace/fastai-docker/pull/8

**Comment by tgajewski** [comment]
https://github.com/Paperspace/fastai-docker/commit/b2ad46fd6ed7570493dff8b10d9df65f16c84dfb
