### ISSUE TITLE
running fastai-v4-lab in paperspace

### ISSUE THREAD

**Issue by ddobrinskiy** [Paperspace/fastai-docker#9]
Hi, I'm trying to run [fastai-v4-lab](https://github.com/Paperspace/fastai-docker/tree/master/fastai-v4-lab) in paperspace.

Here is  what I'm doing:

`new notebook` -> `custom container`

`enter container name` = `paperspace/fastai:2.0-CUDA9.2-complete-4.0-v0.0.12`

`Default command` = `jupyter lab`

![image](https://user-images.githubusercontent.com/29500178/91066280-33d04400-e63a-11ea-9bb0-e8941692f39d.png)

`choose machine` = `GPU+`

But then I get an error, that jupyter token was not found in logs.

Is there a clear mistake I'm making?

![image](https://user-images.githubusercontent.com/29500178/91066368-51051280-e63a-11ea-86b7-87a778fd6c1d.png)

Thanks in advance

**Comment by tgajewski** [comment]
Hi @ddobrinskiy -- You must use `/run.sh` as the default command for all the different types of fastai containers on Gradient. We've also recently added a lab version of the latest v4 with fastbook container here:

paperspace/fastai:2.0-CUDA9.2-fastbook-v0.0.8-lab

And its build setup is reflected in fastai-fastbook-lab in this repo.

**Comment by dkobran** [comment]
@ddobrinskiy Here's a screenshot recapping what @tgajewski mentioned:
![image](https://user-images.githubusercontent.com/8908457/91090061-7d149980-e622-11ea-917d-9a7313f0a9e5.png)
